// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ffactmycfgltbqzrnkro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmYWN0bXljZmdsdGJxenJua3JvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMDg5MzAsImV4cCI6MjA2ODg4NDkzMH0.tEDmU5ych88uH3SXL3aVWGlO-dBJDqlH4albnR0Fp80";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});